[lib]
proc-macro = true

[package]
name = "autorun_config"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full"] }
